version: "3.8"

services:
    app:
        image: php:8.4.5-apache
        container_name: rapid_radio_app
        depends_on:
            - db
        environment:
            - WEB_DOCUMENT_ROOT=/app/repo/public
            - DB_HOST=rapid_radio_db
            - DB_PORT=3306
            - DB_DATABASE=rapid_radio
            - DB_USER=rapid_radio
            - DB_PASSWORD=secret
        volumes:
            - rapid_radio_code:/app
            - rapid_radio_storage:/app/repo/storage
        ports:
            - "8000:80"
        command: |
            bash -c '
            set -e;

            echo "Step 0: System initialization";
            apt-get update && apt-get install -y unzip git libzip-dev curl gnupg2;
            docker-php-ext-install zip pdo pdo_mysql;

            echo "Step 0.1: Installing Composer and Node if missing";
            if [ ! -f /usr/local/bin/composer ]; then
                curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer;
            fi
            if ! command -v node >/dev/null 2>&1; then
                curl -fsSL https://deb.nodesource.com/setup_18.x | bash -;
                apt-get install -y nodejs;
            fi

            echo "Step 1: Preparing repository";
            mkdir -p /app/repo;
            if [ ! -d /app/repo/.git ]; then
                echo "Cloning repo (first run)...";
                git clone --depth 1 https://github.com/xtraorange/rapid-radio.git /app/repo;
            else
                echo "Repo exists – updating...";
                cd /app/repo;
                git reset --hard HEAD;
                git clean -fd;
                git pull origin main;
            fi

            cd /app/repo;

            echo "Step 2: First-run initialization";
            if [ ! -f .initialized ]; then
                echo "Running one-time setup tasks...";

                # Configure Apache only once.
                sed -i "s|/var/www/html|/app/repo/public|g" /etc/apache2/sites-available/000-default.conf;
                if [ ! -f /etc/apache2/conf-available/laravel.conf ]; then
                    echo "<Directory /app/repo/public>" > /etc/apache2/conf-available/laravel.conf;
                    echo "    Options Indexes FollowSymLinks" >> /etc/apache2/conf-available/laravel.conf;
                    echo "    AllowOverride All" >> /etc/apache2/conf-available/laravel.conf;
                    echo "    Require all granted" >> /etc/apache2/conf-available/laravel.conf;
                    echo "</Directory>" >> /etc/apache2/conf-available/laravel.conf;
                    a2enconf laravel.conf;
                fi

                echo "Setting file permissions...";
                mkdir -p storage/logs;
                chown -R www-data:www-data storage bootstrap/cache;
                chmod -R 775 storage bootstrap/cache;

                echo "Configuring Laravel environment...";
                if [ ! -f .env ]; then
                    cp .env.example .env;
                    sed -i "s~^\s*DB_CONNECTION=.*~DB_CONNECTION=mysql~" .env;
                    php artisan key:generate;
                fi

                touch .initialized;
                echo "Initial setup complete.";
            else
                echo "Initial setup already completed. Skipping one-time tasks.";
            fi

            echo "Step 3: Checking for repository updates";
            CURRENT_COMMIT=$(git rev-parse HEAD);
            if [ ! -f .last_commit ] || [ "$CURRENT_COMMIT" != "$(cat .last_commit)" ]; then
                echo "Changes detected (commit changed) – updating dependencies and assets...";

                echo "Running composer install...";
                composer install --no-dev --optimize-autoloader;

                echo "Running npm install and asset build...";
                npm install && npm run build;

                echo "Running database migrations...";
                php artisan migrate --force;

                echo "$CURRENT_COMMIT" > .last_commit;
            else
                echo "No repository changes detected – skipping dependency updates and asset build.";
            fi

            echo "Step 4: Clearing caches and optimizing Laravel";
            php artisan config:clear;
            php artisan route:clear;
            php artisan view:clear;
            php artisan optimize;

            echo "Step 5: Enabling Apache rewrite and launching server";
            a2enmod rewrite;
            apachectl configtest;
            apache2-foreground;
            '
        restart: always

    db:
        image: mysql:8.0
        container_name: rapid_radio_db
        environment:
            - MYSQL_DATABASE=rapid_radio
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=rapid_radio
            - MYSQL_PASSWORD=secret
        volumes:
            - rapid_radio_db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always

volumes:
    rapid_radio_code:
    rapid_radio_storage:
    rapid_radio_db_data:
